server:
  port: 8081

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:mysql://localhost:3306/announcement
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

#  data:
#    redis:
#      host: redis
#      port: 6379

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: info.writtenn@gmail.com
    password: 'hadp yfwc hydb egtu'
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  liquibase:
    change-log: classpath:liquibase/changelog-master.yml

#eureka:
#  client:
#    service-url:
#      defaultZone: http://discovery-service:8010/eureka
